name: docker-image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/chechout@v3
    - name: Build the Docker image
      working-directory: action-test1
      run: docker build . --file Dockerfile
