name: docker-image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile
  login:
    runs-on: ubuntu-latest
    env:
      username: $((secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - name: Log-in
        run: docker login --username=$username --password=$password
